spring:
  application:
    name: book-ui3    
    
  datasource:
    url: jdbc:mysql://mysql:3306/bookdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect    

server:
  port: 8098
  
  
  
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka


    
logging:
  path: /tmp/thyme/logs    
      