apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-ui3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-ui3
  template:
    metadata:
      labels:
        app: book-ui3
    spec:
      containers:
      - name: book-ui3
        image: yklee2002/book-ui3:latest
        ports:
        - containerPort: 8098
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"       
        
---
apiVersion: v1
kind: Service
metadata:
  name: book-ui3-service
spec:
  selector:
    app: book-ui3
  ports:
  - protocol: TCP
    port: 8098
    targetPort: 8098
    nodePort: 30111
  type: NodePort
