apiVersion: apps/v1
kind: Deployment
metadata:
  name: imageserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imageserver
  template:
    metadata:
      labels:
        app: imageserver
    spec:
      containers:
      - name: imageserver
        image: yklee2002/imageserver:latest
        ports:
        - containerPort: 8100
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"        
        volumeMounts:
        - name: upload-storage
          mountPath: /data/uploads
      volumes:
      - name: upload-storage
        persistentVolumeClaim:
          claimName: upload-pvc        
---
apiVersion: v1
kind: Service
metadata:
  name: imageserver-service  # ✅ 소문자만 사용
spec:
  selector:
    app: imageserver
  ports:
  - protocol: TCP
    port: 8100
    targetPort: 8100
    nodePort: 30115
  type: NodePort
